# Generated by Django 6.0.3 on 2026-04-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_userstatus_alter_group_options_group_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('is_online', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='userstatus',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userstatus',
            name='group',
        ),
        migrations.RemoveField(
            model_name='userstatus',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chatapp_mes_user_id_eafa2a_idx',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.AddField(
            model_name='message',
            name='session_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='user_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['session_id', 'timestamp'], name='chatapp_mes_session_8308a5_idx'),
        ),
        migrations.DeleteModel(
            name='UserStatus',
        ),
        migrations.RemoveField(
            model_name='message',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
