# Generated by Django 6.0.3 on 2026-04-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_auto_activity_tracking'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='group',
            new_name='chatapp_gro_last_ac_62963f_idx',
            old_name='chatapp_group_last_activity_idx',
        ),
        migrations.RenameIndex(
            model_name='group',
            new_name='chatapp_gro_created_b88466_idx',
            old_name='chatapp_group_created_at_idx',
        ),
        migrations.AlterField(
            model_name='group',
            name='last_activity',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
