# Generated by Django 6.0.3 on 2026-04-08 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_message_audio_mime_type'),
        ('chatapp', '0006_rename_chatapp_group_last_activity_idx_chatapp_gro_last_ac_62963f_idx_and_more'),
    ]

    operations = [
    ]
