# Generated by Django 6.0.3 on 2026-04-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0009_message_translated_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='normalized_content',
            field=models.TextField(blank=True, help_text='Professional English version of message (sent to receivers)', null=True),
        ),
    ]
