# Auto-generated by Django migration system
# Migration to add explicit tamil_content and english_content fields for automatic bilingual storage

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0009_message_translated_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tamil_content',
            field=models.TextField(blank=True, null=True, help_text='Tamil version of the message (auto-translated)'),
        ),
        migrations.AddField(
            model_name='message',
            name='english_content',
            field=models.TextField(blank=True, null=True, help_text='Professional English version of the message'),
        ),
    ]
