# Generated by Django 6.0.3 on 2026-04-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0010_message_normalized_content'),
        ('chatapp', '0011_add_bilingual_content'),
    ]

    operations = [
    ]
