# Generated by Django 6.0.3 on 2026-04-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0012_merge_20260410_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoususer',
            name='language_mode',
            field=models.CharField(choices=[('english', 'English Mode - Display only English, reject Tamil/Tanglish'), ('tamil', 'Tamil Mode - Display only Tamil, accept Tamil/English input')], default='english', help_text='User language display mode: English only or Tamil only', max_length=10),
        ),
    ]
