# Generated by Django 6.0.3 on 2026-04-17 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0013_anonymoususer_language_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletions', to='chatapp.message')),
            ],
            options={
                'indexes': [models.Index(fields=['message', 'session_id'], name='chatapp_del_message_30b421_idx')],
                'unique_together': {('message', 'session_id')},
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chatapp.group')),
            ],
            options={
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['group', 'last_seen'], name='chatapp_gro_group_i_374c55_idx')],
                'unique_together': {('group', 'session_id')},
            },
        ),
    ]
