# Generated by Django 6.0.3 on 2026-04-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0014_deletedmessage_groupmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio_file_english',
            field=models.FileField(blank=True, help_text='English version of voice message', null=True, upload_to='voice_messages/'),
        ),
        migrations.AddField(
            model_name='message',
            name='audio_file_tamil',
            field=models.FileField(blank=True, help_text='Tamil version of voice message', null=True, upload_to='voice_messages/'),
        ),
    ]
