# Generated by Django 6.0.3 on 2026-05-02 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0016_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deletedmessage',
            options={'ordering': ['-deleted_at']},
        ),
        migrations.RemoveIndex(
            model_name='deletedmessage',
            name='chatapp_del_message_30b421_idx',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='accepted_at',
            field=models.DateTimeField(blank=True, help_text='When was user approved', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='accepted_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_accepted',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='Admin approval status for user', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Is user an admin?'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user', 'is_accepted'], name='chatapp_use_user_id_72f1e8_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['is_accepted'], name='chatapp_use_is_acce_ae5d37_idx'),
        ),
    ]
