# Generated by Django 6.0.4 on 2026-05-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0017_alter_deletedmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deletedmessage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='chatapp_use_user_id_72f1e8_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='chatapp_use_is_acce_ae5d37_idx',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddIndex(
            model_name='deletedmessage',
            index=models.Index(fields=['message', 'session_id'], name='chatapp_del_message_30b421_idx'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='accepted_by',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
    ]
