# Generated by Django 6.0.4 on 2026-05-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0018_alter_deletedmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile Number'),
        ),
    ]
