# Generated by Django 6.0.3 on 2026-05-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0022_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoususer',
            name='language_mode',
            field=models.CharField(default='english', help_text='User language display mode (e.g., english, tamil, hindi, etc.)', max_length=50),
        ),
    ]
