# Generated by Django 6.0.3 on 2026-05-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0023_alter_anonymoususer_language_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='translations',
            field=models.TextField(blank=True, default='', help_text='Legacy translations field (deprecated)', null=True),
        ),
    ]
