# Generated by GitHub Copilot

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0024_message_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio_file_hindi',
            field=models.FileField(upload_to='voice_messages/', blank=True, help_text='Hindi version of voice message', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='audio_file_malayalam',
            field=models.FileField(upload_to='voice_messages/', blank=True, help_text='Malayalam version of voice message', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='audio_file_kannada',
            field=models.FileField(upload_to='voice_messages/', blank=True, help_text='Kannada version of voice message', null=True),
        ),
    ]
