# Generated by Django 6.0.4 on 2026-05-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0025_message_audio_file_hindi_malayalam_kannada'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('source_language', models.CharField(blank=True, default='auto', max_length=50)),
                ('target_language', models.CharField(max_length=50)),
                ('source_text', models.TextField(blank=True, null=True)),
                ('translated_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='anonymoususer',
            index=models.Index(fields=['is_online', 'last_seen'], name='chatapp_ano_is_onli_c2d32a_idx'),
        ),
        migrations.AddIndex(
            model_name='anonymoususer',
            index=models.Index(fields=['session_id'], name='chatapp_ano_session_653c36_idx'),
        ),
        migrations.AddIndex(
            model_name='anonymoususer',
            index=models.Index(fields=['language_mode'], name='chatapp_ano_languag_cc8105_idx'),
        ),
        migrations.AddIndex(
            model_name='deletedmessage',
            index=models.Index(fields=['session_id'], name='chatapp_del_session_96debc_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type'], name='chatapp_mes_message_bc0f68_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_deleted'], name='chatapp_mes_is_dele_044f09_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['timestamp'], name='chatapp_mes_timesta_9d0561_idx'),
        ),
        migrations.AddIndex(
            model_name='translationcache',
            index=models.Index(fields=['source_hash', 'source_language', 'target_language'], name='chatapp_tra_source__e4a98e_idx'),
        ),
        migrations.AddIndex(
            model_name='translationcache',
            index=models.Index(fields=['last_used_at'], name='chatapp_tra_last_us_0be16f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='translationcache',
            unique_together={('source_hash', 'source_language', 'target_language')},
        ),
    ]
