# Generated by Django 6.0.4 on 2026-05-08 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0026_translationcache_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(help_text='Target language (e.g., english, tamil, hindi)', max_length=50)),
                ('translated_text', models.TextField(blank=True, help_text='Translated text content', null=True)),
                ('audio_file', models.FileField(blank=True, help_text='Audio file for this language', null=True, upload_to='voice_messages/')),
                ('audio_mime_type', models.CharField(default='audio/mpeg', help_text='MIME type of audio file', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_translations', to='chatapp.message')),
            ],
            options={
                'indexes': [models.Index(fields=['message', 'language'], name='chatapp_mes_message_42bc13_idx'), models.Index(fields=['language'], name='chatapp_mes_languag_415045_idx'), models.Index(fields=['created_at'], name='chatapp_mes_created_7976ae_idx')],
                'unique_together': {('message', 'language')},
            },
        ),
    ]
