# Generated by Django 6.0.4 on 2026-05-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0027_messagetranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio_file_telugu',
            field=models.FileField(blank=True, help_text='Telugu version of voice message', null=True, upload_to='voice_messages/'),
        ),
    ]
