# Generated by Django 6.0.4 on 2026-05-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0028_message_audio_file_telugu'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio_file_bengali',
            field=models.FileField(blank=True, help_text='Bengali version of voice message', null=True, upload_to='voice_messages/'),
        ),
        migrations.AddField(
            model_name='message',
            name='audio_file_gujarati',
            field=models.FileField(blank=True, help_text='Gujarati version of voice message', null=True, upload_to='voice_messages/'),
        ),
        migrations.AddField(
            model_name='message',
            name='audio_file_marathi',
            field=models.FileField(blank=True, help_text='Marathi version of voice message', null=True, upload_to='voice_messages/'),
        ),
        migrations.AddField(
            model_name='message',
            name='audio_file_punjabi',
            field=models.FileField(blank=True, help_text='Punjabi version of voice message', null=True, upload_to='voice_messages/'),
        ),
        migrations.AddField(
            model_name='message',
            name='audio_file_urdu',
            field=models.FileField(blank=True, help_text='Urdu version of voice message', null=True, upload_to='voice_messages/'),
        ),
    ]
